name: vcpkg binary cache (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest
    env:
      FEED_URL: https://nuget.pkg.github.com/sakgoyal/index.json
      USERNAME: sakgoyal
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/sakgoyal/index.json,readwrite"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build vcpkg using Python script
        run: python3 ${{ github.workspace }}/Toolchain/buildVcpkg.py

      - name: Configure NuGet auth
        shell: pwsh
        run: |
          $vcpkg = "${{ github.workspace }}/Build/vcpkg/vcpkg.exe"
          &$vcpkg fetch nuget `
            sources add `
            -Source "$env:FEED_URL" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "$env:USERNAME" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          &$vcpkg fetch nuget `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "$env:FEED_URL"

      - name: Install dependencies
        run: ${{ github.workspace }}/Build/vcpkg/vcpkg.exe install --triplet x64-windows
