name: vcpkg binary cache (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest
    env:
      FEED_URL: https://nuget.pkg.github.com/sakgoyal/index.json
      USERNAME: sakgoyal
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/sakgoyal/index.json,readwrite"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build vcpkg
        run: python3 ${{ github.workspace }}/Toolchain/buildVcpkg.py

      - name: Install dependencies
        run: ${{ github.workspace }}/Build/vcpkg/vcpkg.exe install --triplet x64-windows

      - name: Upload binary cache to NuGet
        run: ${{ github.workspace }}/Build/vcpkg/vcpkg.exe cache --nuget --nuget-source ${{ env.FEED_URL }} --nuget-user ${{ env.USERNAME }} --nuget-password ${{ secrets.GITHUB_TOKEN }}
