name: vcpkg binary cache (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest
    env:
      FEED_URL: https://nuget.pkg.github.com/sakgoyal/index.json
      USERNAME: sakgoyal
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/sakgoyal/index.json,readwrite"
      X_VCPKG_ASSET_SOURCES: "clear;x-azurl,https://vcpkg-cache.app.ladybird.org/ladybird/source-assets/,,read"

    steps:
      - uses: actions/checkout@v4

      - name: Cache vcpkg build
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/Build/vcpkg
            ${{ github.workspace }}/Build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: python3 ${{ github.workspace }}/Toolchain/buildVcpkg.py

      - name: Configure NuGet feed for vcpkg
        shell: pwsh
        run: |
          # Fetch NuGet client from vcpkg
          $nugetExe = & "${{ github.workspace }}/Build/vcpkg/vcpkg.exe" fetch nuget | Select-Object -Last 1
          # Add GitHub Packages source with credentials
          & $nugetExe sources add `
            -Name GitHubPackages `
            -Source $env:FEED_URL `
            -StorePasswordInClearText `
            -UserName $env:USERNAME `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          # Set API key
          & $nugetExe setapikey `
            "${{ secrets.GITHUB_TOKEN }}" `
            -Source $env:FEED_URL

      - name: Install dependencies
        run: ${{ github.workspace }}/Build/vcpkg/vcpkg.exe install --triplet x64-windows

      - name: Upload binary cache to NuGet
        run: ${{ github.workspace }}/Build/vcpkg/vcpkg.exe cache --nuget --nuget-source ${{ env.FEED_URL }} --nuget-user ${{ env.USERNAME }} --nuget-password ${{ secrets.GITHUB_TOKEN }}
