name: vcpkg binary cache (Windows)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest
    env:
      FEED_URL: https://nuget.pkg.github.com/sakgoyal/index.json
      USERNAME: sakgoyal
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/sakgoyal/index.json,readwrite"

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Configure NuGet auth
        run: |
          $nuget = & "$env:GITHUB_WORKSPACE\vcpkg\vcpkg.exe" fetch nuget | Select-String "nuget.exe" | ForEach-Object { $_.ToString().Trim() }
          & $nuget sources add -Source "$env:FEED_URL" -Name "GitHubPackages" -UserName "$env:USERNAME" -Password "${{ secrets.GITHUB_TOKEN }}" -StorePasswordInClearText
          & $nuget setapikey "${{ secrets.GITHUB_TOKEN }}" -Source "$env:FEED_URL"

      - name: Install dependencies (build + upload binaries)
        run: .\vcpkg\vcpkg.exe install --triplet x64-windows
